const sliderActionTypes = {
	LEFT_BUTTON_CLICKED: "LEFT_BUTTON_CLICKED",
	RIGHT_BUTTON_CLICKED: "RIGHT_BUTTON_CLICKED",
	SET_AS_CURRENT: "SET_AS_CURRENT",
	SET_AS_PREVIOUS: "SET_AS_PREVIOUS",
	SET_AS_NEXT: "SET_AS_NEXT"
};

export default sliderActionTypes;